CREATE DATABASE IF NOT EXISTS loja_agricola CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE loja_agricola;

CREATE TABLE tipo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE unidade (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    sigla VARCHAR(10) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE insumo (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    quantidade DOUBLE NOT NULL DEFAULT 0,
    preco DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    tipo_id BIGINT,
    unidade_id BIGINT,
    FOREIGN KEY (tipo_id) REFERENCES tipo(id) ON DELETE SET NULL,
    FOREIGN KEY (unidade_id) REFERENCES unidade(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE ferramenta (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    quantidade INT NOT NULL DEFAULT 0,
    preco DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    tipo_id BIGINT,
    FOREIGN KEY (tipo_id) REFERENCES tipo(id) ON DELETE SET NULL
) ENGINE=InnoDB;